version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1
  # vpn-macos: aetna/vpn-macos@1

workflows:
  welcome:
    jobs:
      - welcome/run
  main:
    jobs:
      - start-gcp:
          context: gcp-self-destroy

jobs:
  start-gcp:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: echo $GCLOUD_SERVICE_KEY
      - run: echo $GCLOUD_SERVICE_KEY > ./gcloud-key.json
      - run: cat ./gcloud-key.json
      - run: |
          gcloud auth activate-service-account --key-file=./gcloud-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: |
          gcloud compute instances create
          self-destruct-01
          --zone=us-central1-c
          --image-family=ubuntu-1804-lts --image-project=ubuntu-os-cloud --boot-disk-size=200GB
          --scopes=https://www.googleapis.com/auth/compute,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/trace.append,https://www.googleapis.com/auth/devstorage.read_only
          --metadata SELF_DESTRUCT_INTERVAL_MINUTES=2
          --metadata-from-file startup-script=startup-script.sh

