version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

workflows:
  main:
    jobs:
      - start-gcp:
          context: gcp-self-destroy
      - job1:
          requires:
            - start-gcp
      - job2:
          requires:
            - start-gcp

jobs:
  start-gcp:
    environment:
      CIRCLE_PIPELINE_ID: "<< pipeline.id >>"
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: "This is pipeline ID << pipeline.id >>"
          command: echo "This is pipeline ID ${CIRCLE_PIPELINE_ID}"
      - run:
          name: "Write GCLOUD_SERVICE_KEY to file: ./gcloud-key.json"
          command: echo $GCLOUD_SERVICE_KEY > ./gcloud-key.json
      - run: |
          gcloud auth activate-service-account --key-file=./gcloud-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: >
          gcloud compute instances create
          circle-${CIRCLE_PIPELINE_ID}
          --zone=us-central1-c
          --image-family=ubuntu-1804-lts
          --image-project=ubuntu-os-cloud
          --boot-disk-size=200GB
          --scopes=https://www.googleapis.com/auth/compute,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/trace.append,https://www.googleapis.com/auth/devstorage.read_only
          --metadata SELF_DESTRUCT_INTERVAL_MINUTES=2,CIRCLE_API_TOKEN=${CIRCLE_API_TOKEN},CIRCLE_PIPELINE_ID=${CIRCLE_PIPELINE_ID}
          --metadata-from-file startup-script=gcp-keepalive.py
      - run: >
          gcloud compute instances describe circle-${CIRCLE_PIPELINE_ID}
          --format='get(networkInterfaces[0].accessConfigs[0].natIP)' > ./gcp_instance_ip.txt
      - store_artifacts:
          path: ./gcp_instance_ip.txt

  job1:
    docker:
      - image: python3.7
    steps:
      - run:
          name: "Sleep..."
          command: sleep 30
  job2:
    docker:
      - image: python3.7
    steps:
      - run:
          name: "Sleep..."
          command: sleep 30
