version: 2.1

orbs:
  gcloud: circleci/gcp-cli@1.8.3

executors:
  gcloudsdk:
    docker:
      - image: google/cloud-sdk

  python_3-7:
    docker:
      - image: python:3.7

workflows:
  main:
    jobs:
      - start-gcp:
          context: gcp-self-destroy
      - job1:
          requires:
            - start-gcp
      - job2:
          requires:
            - start-gcp

jobs:
  start-gcp:
    environment:
      CIRCLE_PIPELINE_ID: "<< pipeline.id >>"
    executor: gcloudsdk
    steps:
      - checkout
      - run:
          name: "This is pipeline ID << pipeline.id >>"
          command: echo "This is pipeline ID ${CIRCLE_PIPELINE_ID}"
      - gcloud/initialize:
          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-compute-zone: GOOGLE_COMPUTE_ZONE
          google-project-id: GOOGLE_PROJECT_ID
      - run: >
          gcloud compute instances create
          circle-${CIRCLE_PIPELINE_ID}
          --zone=us-central1-c
          --image-family=ubuntu-1804-lts
          --image-project=ubuntu-os-cloud
          --boot-disk-size=200GB
          --scopes=https://www.googleapis.com/auth/compute,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/trace.append,https://www.googleapis.com/auth/devstorage.read_only
          --metadata SELF_DESTRUCT_INTERVAL_MINUTES=2,CIRCLE_API_TOKEN=${CIRCLE_API_TOKEN},CIRCLE_PIPELINE_ID=${CIRCLE_PIPELINE_ID}
          --metadata-from-file startup-script=gcp-keepalive.py
      - run: >
          gcloud compute instances describe circle-${CIRCLE_PIPELINE_ID}
          --zone=us-central1-c
          --format='get(networkInterfaces[0].accessConfigs[0].natIP)' > ./gcp_instance_ip.txt
      - store_artifacts:
          path: ./
      - persist_to_workspace:
          root: ./
          path: ./

  job1:
    executor: python_3-7
    steps:
      - attach_workspace:
          at: ./
      - run: ping -c 1 $(cat ./gcp_instance_ip.txt)
      - run:
          name: "Sleep..."
          command: sleep 30
  job2:
    executor: python_3-7
    steps:
      - attach_workspace:
          at: ./
      - run: ping -c 1 $(cat ./gcp_instance_ip.txt)
      - run:
          name: "Sleep..."
          command: sleep 30
